name: whisp
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  diacritic: ^0.1.6
  material_symbols_icons: ^4.2811.0
  intl: ^0.20.2
  image_picker: ^1.1.2
  supabase_flutter: ^2.8.4
  flutter_webrtc: ^0.13.1+hotfix.1
  uuid: ^4.5.1
  flutter_dotenv: ^5.2.1
  font_awesome_flutter: ^10.8.0
  file_picker: ^10.1.1
  video_player: ^2.9.5
  url_launcher: ^6.3.1
  sqflite: ^2.4.2
  path: ^1.9.1
  connectivity_plus: ^6.1.3
  image_cropper: ^9.1.0
  flutter_slidable: ^4.0.0
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^19.1.0
  shared_preferences: ^2.5.3
  yet_another_json_isolate: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
