name: whisp
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  diacritic: ^0.1.6
  intl: ^0.20.2
  image_picker: ^1.1.2
  supabase_flutter: ^2.8.4
  flutter_webrtc: ^0.13.1+hotfix.1
  flutter_dotenv: ^5.2.1
  font_awesome_flutter: ^10.8.0
  file_picker: ^10.1.1
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.3
  image_cropper: ^9.1.0
  flutter_slidable: ^4.0.0
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^19.1.0
  path_provider: ^2.1.5
  app_links: ^6.4.0
  permission_handler: ^12.0.0+1
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  get_thumbnail_video: ^0.7.3
  image_size_getter: ^2.4.0
  video_player: ^2.9.5
  chewie: ^1.11.3
  mime: ^2.0.0
  audioplayers: ^6.4.0
  infinite_scroll_pagination: ^5.0.0
  text_scroll: ^0.2.0
  waveform_recorder: ^1.7.0
  waveform_flutter: ^1.2.0
  waved_audio_player: ^1.3.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
